# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing

@typing.final
class FileContentIterator:
    def __iter__(self) -> FileContentIterator: ...
    def __next__(self) -> typing.Optional[tuple[builtins.str, typing.Any]]: ...

@typing.final
class FrioBuffer:
    ...

def fetch(files: typing.Sequence[builtins.str], chunk_size: builtins.int = 0, threads: builtins.int = 1) -> FileContentIterator: ...

